# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tmp_v1.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(679, 444)
        MainWindow.setStyleSheet("")
        self.mian_widget = QtWidgets.QWidget(MainWindow)
        self.mian_widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mian_widget.setStyleSheet("")
        self.mian_widget.setObjectName("mian_widget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.mian_widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(29, 29, 611, 311))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.main_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.main_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setObjectName("main_layout")
        self.label_url = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_url.sizePolicy().hasHeightForWidth())
        self.label_url.setSizePolicy(sizePolicy)
        self.label_url.setStyleSheet("")
        self.label_url.setObjectName("label_url")
        self.main_layout.addWidget(self.label_url, 0, 0, 1, 1)
        self.label_port = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_port.setObjectName("label_port")
        self.main_layout.addWidget(self.label_port, 0, 2, 1, 1)
        self.url_port = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.url_port.sizePolicy().hasHeightForWidth())
        self.url_port.setSizePolicy(sizePolicy)
        self.url_port.setObjectName("url_port")
        self.main_layout.addWidget(self.url_port, 0, 3, 1, 1)
        self.child_layout = QtWidgets.QGridLayout()
        self.child_layout.setObjectName("child_layout")
        self.label_method = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_method.setAlignment(QtCore.Qt.AlignCenter)
        self.label_method.setObjectName("label_method")
        self.child_layout.addWidget(self.label_method, 0, 3, 1, 1)
        self.label_content_type = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_content_type.setAlignment(QtCore.Qt.AlignCenter)
        self.label_content_type.setObjectName("label_content_type")
        self.child_layout.addWidget(self.label_content_type, 0, 2, 1, 1)
        self.label_status = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setObjectName("label_status")
        self.child_layout.addWidget(self.label_status, 0, 4, 1, 1)
        self.label_path = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_path.setAlignment(QtCore.Qt.AlignCenter)
        self.label_path.setObjectName("label_path")
        self.child_layout.addWidget(self.label_path, 0, 1, 1, 1)
        self.label_opearte = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_opearte.setAlignment(QtCore.Qt.AlignCenter)
        self.label_opearte.setObjectName("label_opearte")
        self.child_layout.addWidget(self.label_opearte, 0, 5, 1, 1)
        self.dis_row_layout = QtWidgets.QGridLayout()
        self.dis_row_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.dis_row_layout.setObjectName("dis_row_layout")
        self.dis_method = QtWidgets.QLabel(self.gridLayoutWidget)
        self.dis_method.setText("")
        self.dis_method.setObjectName("dis_method")
        self.dis_row_layout.addWidget(self.dis_method, 0, 3, 1, 1)
        self.dis_status = QtWidgets.QLabel(self.gridLayoutWidget)
        self.dis_status.setText("")
        self.dis_status.setObjectName("dis_status")
        self.dis_row_layout.addWidget(self.dis_status, 0, 4, 1, 1)
        self.dis_ck_box = QtWidgets.QCheckBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dis_ck_box.sizePolicy().hasHeightForWidth())
        self.dis_ck_box.setSizePolicy(sizePolicy)
        self.dis_ck_box.setText("")
        self.dis_ck_box.setObjectName("dis_ck_box")
        self.dis_row_layout.addWidget(self.dis_ck_box, 0, 0, 1, 1)
        self.dis_type = QtWidgets.QLabel(self.gridLayoutWidget)
        self.dis_type.setText("")
        self.dis_type.setObjectName("dis_type")
        self.dis_row_layout.addWidget(self.dis_type, 0, 2, 1, 1)
        self.dis_path = QtWidgets.QLabel(self.gridLayoutWidget)
        self.dis_path.setText("")
        self.dis_path.setObjectName("dis_path")
        self.dis_row_layout.addWidget(self.dis_path, 0, 1, 1, 1)
        self.dis_operate = QtWidgets.QVBoxLayout()
        self.dis_operate.setObjectName("dis_operate")
        self.dis_btn_modify = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.dis_btn_modify.setObjectName("dis_btn_modify")
        self.dis_operate.addWidget(self.dis_btn_modify)
        self.dis_btn_delete = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.dis_btn_delete.setObjectName("dis_btn_delete")
        self.dis_operate.addWidget(self.dis_btn_delete)
        self.dis_row_layout.addLayout(self.dis_operate, 0, 5, 1, 1)
        self.child_layout.addLayout(self.dis_row_layout, 1, 0, 1, 6)
        self.label_checkout_all = QtWidgets.QCheckBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_checkout_all.sizePolicy().hasHeightForWidth())
        self.label_checkout_all.setSizePolicy(sizePolicy)
        self.label_checkout_all.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_checkout_all.setText("")
        self.label_checkout_all.setObjectName("label_checkout_all")
        self.child_layout.addWidget(self.label_checkout_all, 0, 0, 1, 1)
        self.main_layout.addLayout(self.child_layout, 1, 0, 1, 4)
        self.url_host = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.url_host.setObjectName("url_host")
        self.main_layout.addWidget(self.url_host, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.mian_widget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 679, 23))
        self.menubar.setObjectName("menubar")
        self.menu_run = QtWidgets.QMenu(self.menubar)
        self.menu_run.setObjectName("menu_run")
        self.menu_path = QtWidgets.QMenu(self.menubar)
        self.menu_path.setObjectName("menu_path")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_start = QtWidgets.QAction(MainWindow)
        self.action_start.setObjectName("action_start")
        self.action_stop = QtWidgets.QAction(MainWindow)
        self.action_stop.setObjectName("action_stop")
        self.action_restart = QtWidgets.QAction(MainWindow)
        self.action_restart.setObjectName("action_restart")
        self.action_add = QtWidgets.QAction(MainWindow)
        self.action_add.setObjectName("action_add")
        self.action_new = QtWidgets.QAction(MainWindow)
        self.action_new.setObjectName("action_new")
        self.menu_run.addAction(self.action_start)
        self.menu_run.addAction(self.action_stop)
        self.menu_run.addAction(self.action_restart)
        self.menu_path.addAction(self.action_new)
        self.menubar.addAction(self.menu_run.menuAction())
        self.menubar.addAction(self.menu_path.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_url.setText(_translate("MainWindow", "URL:"))
        self.label_port.setText(_translate("MainWindow", "Port:"))
        self.label_method.setText(_translate("MainWindow", "Method"))
        self.label_content_type.setText(_translate("MainWindow", "Content-Type"))
        self.label_status.setText(_translate("MainWindow", "Status"))
        self.label_path.setText(_translate("MainWindow", "Path"))
        self.label_opearte.setText(_translate("MainWindow", "Operate"))
        self.dis_btn_modify.setText(_translate("MainWindow", "Modify"))
        self.dis_btn_delete.setText(_translate("MainWindow", "Delete"))
        self.menu_run.setTitle(_translate("MainWindow", "Run"))
        self.menu_path.setTitle(_translate("MainWindow", "Path"))
        self.action_start.setText(_translate("MainWindow", "Start"))
        self.action_stop.setText(_translate("MainWindow", "Stop"))
        self.action_restart.setText(_translate("MainWindow", "Restart"))
        self.action_add.setText(_translate("MainWindow", "Add"))
        self.action_new.setText(_translate("MainWindow", "Add"))

