# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tmp.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(534, 408)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(60, 30, 411, 49))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.url_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.url_layout.setContentsMargins(0, 0, 0, 0)
        self.url_layout.setObjectName("url_layout")
        self.label_url = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_url.setObjectName("label_url")
        self.url_layout.addWidget(self.label_url)
        self.url_path = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.url_path.setObjectName("url_path")
        self.url_layout.addWidget(self.url_path)
        self.req_method = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.req_method.setCurrentText("")
        self.req_method.setObjectName("req_method")
        self.url_layout.addWidget(self.req_method)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 100, 411, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.opt_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.opt_layout.setContentsMargins(0, 0, 0, 0)
        self.opt_layout.setObjectName("opt_layout")
        self.status_point = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.status_point.setObjectName("status_point")
        self.opt_layout.addWidget(self.status_point)
        self.btn_start = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_start.setObjectName("btn_start")
        self.opt_layout.addWidget(self.btn_start)
        self.btn_stop = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_stop.setObjectName("btn_stop")
        self.opt_layout.addWidget(self.btn_stop)
        self.btn_restart = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_restart.setObjectName("btn_restart")
        self.opt_layout.addWidget(self.btn_restart)
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(60, 190, 411, 131))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.content_type = QtWidgets.QComboBox(self.formLayoutWidget)
        self.content_type.setObjectName("content_type")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.content_type)
        self.label_ct = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_ct.setObjectName("label_ct")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_ct)
        self.label_text = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_text.setText("")
        self.label_text.setObjectName("label_text")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_text)
        self.content = QtWidgets.QPlainTextEdit(self.formLayoutWidget)
        self.content.setObjectName("content")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.content)
        self.label_file = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_file.setText("")
        self.label_file.setObjectName("label_file")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_file)
        self.btn_file_open = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn_file_open.setObjectName("btn_file_open")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.btn_file_open)
        self.horizontalLayoutWidget_2.raise_()
        self.horizontalLayoutWidget.raise_()
        self.url_path.raise_()
        self.formLayoutWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 534, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.req_method.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_url.setText(_translate("MainWindow", "URL:"))
        self.status_point.setText(_translate("MainWindow", "point"))
        self.btn_start.setText(_translate("MainWindow", "Start"))
        self.btn_stop.setText(_translate("MainWindow", "Stop"))
        self.btn_restart.setText(_translate("MainWindow", "Restart"))
        self.label_ct.setText(_translate("MainWindow", "Content-Type:"))
        self.btn_file_open.setText(_translate("MainWindow", "Open File"))

