# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tmp_v2.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 50, 661, 431))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.layout_main = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.layout_main.setContentsMargins(0, 0, 0, 0)
        self.layout_main.setObjectName("layout_main")
        self.layout_data = QtWidgets.QHBoxLayout()
        self.layout_data.setObjectName("layout_data")
        self.btn_add = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_add.setObjectName("btn_add")
        self.layout_data.addWidget(self.btn_add)
        self.btn_modify = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_modify.setObjectName("btn_modify")
        self.layout_data.addWidget(self.btn_modify)
        self.btn_remove = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_remove.setObjectName("btn_remove")
        self.layout_data.addWidget(self.btn_remove)
        self.layout_main.addLayout(self.layout_data, 2, 4, 1, 3)
        self.label_main = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_main.sizePolicy().hasHeightForWidth())
        self.label_main.setSizePolicy(sizePolicy)
        self.label_main.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_main.setObjectName("label_main")
        self.layout_main.addWidget(self.label_main, 0, 1, 1, 2)
        self.label_host = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_host.sizePolicy().hasHeightForWidth())
        self.label_host.setSizePolicy(sizePolicy)
        self.label_host.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_host.setObjectName("label_host")
        self.layout_main.addWidget(self.label_host, 1, 1, 1, 2)
        self.line_tmp = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_tmp.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_tmp.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_tmp.setObjectName("line_tmp")
        self.layout_main.addWidget(self.line_tmp, 0, 3, 1, 1)
        self.line_info = QtWidgets.QFrame(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_info.sizePolicy().hasHeightForWidth())
        self.line_info.setSizePolicy(sizePolicy)
        self.line_info.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_info.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_info.setObjectName("line_info")
        self.layout_main.addWidget(self.line_info, 2, 3, 1, 1)
        self.label_info = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_info.sizePolicy().hasHeightForWidth())
        self.label_info.setSizePolicy(sizePolicy)
        self.label_info.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_info.setObjectName("label_info")
        self.layout_main.addWidget(self.label_info, 2, 1, 1, 2)
        self.layout_run = QtWidgets.QHBoxLayout()
        self.layout_run.setObjectName("layout_run")
        self.btn_start = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_start.setObjectName("btn_start")
        self.layout_run.addWidget(self.btn_start)
        self.btn_stop = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_stop.setObjectName("btn_stop")
        self.layout_run.addWidget(self.btn_stop)
        self.btn_restart = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_restart.setObjectName("btn_restart")
        self.layout_run.addWidget(self.btn_restart)
        self.layout_main.addLayout(self.layout_run, 0, 4, 1, 3)
        self.edit_host = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.edit_host.setObjectName("edit_host")
        self.layout_main.addWidget(self.edit_host, 1, 3, 1, 2)
        self.widget_data = QtWidgets.QTableWidget(self.gridLayoutWidget)
        self.widget_data.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget_data.setObjectName("widget_data")
        self.widget_data.setColumnCount(6)
        self.widget_data.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.widget_data.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.widget_data.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.widget_data.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.widget_data.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.widget_data.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.widget_data.setHorizontalHeaderItem(5, item)
        self.layout_main.addWidget(self.widget_data, 3, 1, 1, 6)
        self.label_port = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_port.sizePolicy().hasHeightForWidth())
        self.label_port.setSizePolicy(sizePolicy)
        self.label_port.setAlignment(QtCore.Qt.AlignCenter)
        self.label_port.setObjectName("label_port")
        self.layout_main.addWidget(self.label_port, 1, 5, 1, 1)
        self.edit_port = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_port.sizePolicy().hasHeightForWidth())
        self.edit_port.setSizePolicy(sizePolicy)
        self.edit_port.setMaxLength(5)
        self.edit_port.setCursorPosition(0)
        self.edit_port.setObjectName("edit_port")
        self.layout_main.addWidget(self.edit_port, 1, 6, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_add.setText(_translate("MainWindow", "Add"))
        self.btn_modify.setText(_translate("MainWindow", "Modify"))
        self.btn_remove.setText(_translate("MainWindow", "Remove"))
        self.label_main.setText(_translate("MainWindow", "Ver.01"))
        self.label_host.setText(_translate("MainWindow", "Host:"))
        self.label_info.setText(_translate("MainWindow", "Config:"))
        self.btn_start.setText(_translate("MainWindow", "Start"))
        self.btn_stop.setText(_translate("MainWindow", "Stop"))
        self.btn_restart.setText(_translate("MainWindow", "Restart"))
        self.edit_host.setText(_translate("MainWindow", "http://"))
        item = self.widget_data.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Path"))
        item = self.widget_data.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Method"))
        item = self.widget_data.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Head"))
        item = self.widget_data.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Status"))
        item = self.widget_data.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Operate"))
        self.label_port.setText(_translate("MainWindow", "Port:"))

